// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvfavlvhvminjpfmhypm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2ZmF2bHZodm1pbmpwZm1oeXBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjc5MDgsImV4cCI6MjA2OTY0MzkwOH0.JRDmgFKteUopqYYaWc3xi_QJjIVE3vgE6Vv9cnN2YPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});